export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_INVENTORY_BEGIN = "CREATE_INVENTORY_BEGIN";
export const CREATE_INVENTORY_SUCCESS = "CREATE_INVENTORY_SUCCESS";
export const CREATE_INVENTORY_ERROR = "CREATE_INVENTORY_ERROR";

export const GET_INVENTORY_BEGIN = "GET_INVENTORY_BEGIN";
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";

export const SET_EDIT_INVENTORY = "SET_EDIT_INVENTORY";

export const DELETE_INVENTORY_BEGIN = "DELETE_INVENTORY_BEGIN";

export const EDIT_INVENTORY_BEGIN = "EDIT_INVENTORY_BEGIN";
export const EDIT_INVENTORY_SUCCESS = "EDIT_INVENTORY_SUCCESS";
export const EDIT_INVENTORY_ERROR = "EDIT_INVENTORY_ERROR";

export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const CHANGE_PAGE = "CHANGE_PAGE";
